quilt module users can bring an existing network
quiltdata/iac pull request #26
Opened 2023-09-23 17:36 UTC by akarve

Things I considered by decided not to do:
1. `existing_network` as `map(str)` but validation conditions can only reference themselves and this was limiting and made the code hairier
2. Could have made `cidr` nullable but this is problematic for the locals in `vpc` (and would complicate that code) so it remains as validation of the block size and even existing_network users need to pass `cidr`.

2023-09-25 19:59 UTC, dimaryaz requested changes

2023-09-26 16:37 UTC, dimaryaz commented on modules/quilt/variables.tf
>    default     = null
Should the default now be `""`?

2023-09-26 16:37 UTC, dimaryaz commented on modules/quilt/variables.tf
> +  validation {
If Cidr validation is in the VPC module, then maybe subnets should be, too?

2023-09-26 17:49 UTC, akarve commented on modules/quilt/variables.tf
>    default     = null
In theory `nullable=true` is the default and this change has no effect. In practice, I will revert this change.

2023-09-26 17:50 UTC, akarve commented on modules/quilt/variables.tf
> +  validation {
Sure that makes sense.

2023-09-26 19:19 UTC, dimaryaz approved these changes

2023-09-26 19:19 UTC, dimaryaz commented on modules/quilt/variables.tf
> +  description = "Only needed when var.internal == False (for NAT & load balancer)."
Lowercase false?

2023-09-26 19:33 UTC, akarve commented on modules/quilt/variables.tf
> +  description = "Only needed when var.internal == False (for NAT & load balancer)."
Fixed

2023-09-26 19:34 UTC, merged