Clarify pinning by branch
quiltdata/iac pull request #66
Opened 2024-07-17 22:06 UTC by akarve

2024-07-18 00:36 UTC, QuiltSimon requested changes

2024-07-18 00:36 UTC, QuiltSimon commented on README.md
Can you add an example of how you'd find this hash? Might sound basic but I've gotten that question. Is there a github doc that we can direct them toward? Does it need to be the whole hash?

2024-07-18 01:23 UTC, akarve commented on README.md
> +    1. Update the `quilt.source=` pin to the newest `main` commit hash from the present repository.
```suggestion
    1. Update the `quilt.source=` pin to the newest
    [`main` commit hash](https://github.com/quiltdata/iac/commits/main/)
    from the present repository.
```

2024-07-23 18:11 UTC, QuiltSimon approved these changes

2024-07-24 22:52 UTC, merged